### ISSUE TITLE
ADB Port Finding

### ISSUE THREAD

**Issue by iamsr** [baalexander/node-portscanner#61]
While searching for available adb device on port 5555 following error thrown --

This is my code to find adb device :
 for (let i = 0; i <= 255; i++) {
      const scannedIp = baseIp + i;
      portscanner
        .checkPortStatus(port, scannedIp)
        .then(status => {
          if (status === 'open') {
            log.debug('Found open port at:', scannedIp);
          }
        })
        .catch(err => {
          log.error('Unable to scan port:', err);
        });
    }

Error thrown ---

22:22:40.977 › Unable to scan port: Error: connect ENETUNREACH 192.168.43.255:5555 - Local (0.0.0.0:0)
    at internalConnect (net.js:833:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at net.js:924:9
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
22:22:40.977 › Unable to scan port: Error: connect ENETUNREACH 192.168.43.0:5555 - Local (0.0.0.0:0)
    at internalConnect (net.js:833:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at net.js:924:9
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

Please let me know if you can help....

**Comment by laggingreflex** [comment]
Hi there. 

I notice you're using Promises (async operation) in a for-loop (sync operation) which isn't probably what you wanna do. Checkout https://stackoverflow.com/questions/40328932/javascript-es6-promise-for-loop/40329190

As for the error itself, isn't it expected? You're scanning a lot of IPs, some of which would most probably be unreachable, no? Hence the error. I think you might wanna ignore that error and just get the IP that resolves succesfully. 

I'm closing this since it's a question, please feel free to continue the discussion. Or better yet, try http://stackoverflow.com/

**Comment by iamsr** [comment]
Thanks man. I got it wrong completely.
